### ISSUE TITLE
Klarna partial authorization

### ISSUE THREAD

**Issue by manju613** [Adyen/adyen-commercetools#1030]
Hi, we have scenario - where in we have to send all cart line items total amount , tax etc. But we need to Authorize less from klarna.

Is this supported with Klarna?

Ex:
Line item 1 : $100
Line item 2 : $200

But since we are supporting split payments, shopper can pay $150 from card and remaining 150 from klarna. Did klarna support split payment like this?

**Comment by lojzatran** [comment]
Hi @manju613 

Your request is specific to Adyen functionality. We do not have deep expertise in Adyen as this repo is for integration between Adyen and commercetools.

For your question please open a support ticket in Adyen: https://www.adyen.help/hc/en-us

Thank you.

**Comment by butenkor** [comment]
If you know that you are going to pay the half by Klarna and another half by card why don't you create 2 [commercetools payments](https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#step-2-creating-a-commercetools-payment) with 2 different amounts?

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x CommerceTools integration has changed ownership. From July 1st 2023, Adyen has taken over support / maintenance tasks for this integration from CommerceTools. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
