### ISSUE TITLE
Notification module cannot find capture with custom reference

### ISSUE THREAD

**Issue by LSshopmacher** [Adyen/adyen-commercetools#1038]
follow up for https://github.com/commercetools/commercetools-adyen-integration/issues/975

We added the custom reference for the refund. To match them to a single/specific capture, we added custom reference values for every capture. This is working fine now (match a specific refund to a specific capture).

But the notification module now has a problem, it cannot find the correct capture (because of the custom reference field instead of the merchant reference).

Perhaps you need to enter a fallback to find the correct payment in the notification module if the custom reference field has been used?

**Comment by lojzatran** [comment]
Hi @LSshopmacher 

Thank you for the issue. I can confirm this is a bug.

We will check it and come up with the solution as soon as possible.

**Comment by baumwolli** [comment]
Hi,

we have the same issue. The custom reference will be set in adyen but the payment will not be set to payed. The notification module reports: "Payment with merchantReference: customReference was not found"

**Comment by leungkinghin** [comment]
@baumwolli Thanks for the report. It is an known issue for us, and we are going to fix it in coming weeks

**Comment by leungkinghin** [comment]
@baumwolli We have already provided a fix in the latest release
https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v10.1.1

Please feel free to let us know if you have further question.

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x CommerceTools integration has changed ownership. From July 1st 2023, Adyen has taken over support / maintenance tasks for this integration from CommerceTools. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x CommerceTools integration has changed ownership. From July 1st 2023, Adyen has taken over support / maintenance tasks for this integration from CommerceTools. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
