### ISSUE TITLE
Challenge Response Issue with time out offers

### ISSUE THREAD

**Issue by alexsedano010** [Adyen/adyen-commercetools#1083]
Hi I have a question, I deployed the commercetools extension (with AWS lambdas), and we have detected by Adyen Support that we have a time-out at the ACS during 3DS authentication. This time-out occurs in an offer with a merchant reference; nonetheless, we also have a payment with the same merchant reference that was successful (same card and user info); tracking it down, it seems like the user wasn't affected by it. But occasionally, we see this same error on the offers. Does the commercetools extension V10.x.x handle the offers in some way different than payments? Is this handle by the notification module? Or is this an expected behavior? 

All help is greatly appreciated, thank you in advance.

**Comment by butenkor** [comment]
Hi, 

> we have a time-out at the ACS during 3DS authentication. This time-out occurs in an offer with a merchant reference

Could you please elaborate how is this related to the integration?

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x CommerceTools integration has changed ownership. From July 1st 2023, Adyen has taken over support / maintenance tasks for this integration from CommerceTools. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
