### ISSUE TITLE
upgrading to v11

### ISSUE THREAD

**Issue by davie** [Adyen/adyen-commercetools#1087]
Hi, 
we've been using this commercetools adyen integration for some time - many thanks for maintaining it!
I see that v11 has been marked as a major breaking change, requiring upgrading the adyen web components to v5, which then requires a change to use the /sessions endpoint rather than the existing approach.

Is there documentation anywhere explaining what is required for this upgrade, and how to do it without downtime?
The upgrade appears to require updating both the frontend components and the backend notification and extension modules at the same time.

Thanks,
Davie

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x CommerceTools integration has changed ownership. From July 1st 2023, Adyen has taken over support / maintenance tasks for this integration from CommerceTools. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
