### ISSUE TITLE
undefined not handled properly

### ISSUE THREAD

**Issue by jakinluk** [Adyen/adyen-commercetools#1091]
https://github.com/commercetools/commercetools-adyen-integration/blob/bc2c28fd61a2b0dd3c63ccb50e05c96caa96b7c9/notification/src/handler/notification/notification.handler.js#L57

payment might be undefined then the condition evaluates to `true`
this is causing an unhandled non-repeatable error thrown here https://github.com/commercetools/commercetools-adyen-integration/blob/bc2c28fd61a2b0dd3c63ccb50e05c96caa96b7c9/notification/src/handler/notification/notification.handler.js#L73

resulting in an invalid response returned to Adyen

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x CommerceTools integration has changed ownership. From July 1st 2023, Adyen has taken over support / maintenance tasks for this integration from CommerceTools. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
