### ISSUE TITLE
Add possibility to migrate from v4 to v5 smoothly

### ISSUE THREAD

**Issue by Fifciu** [Adyen/adyen-commercetools#1101]
**Is your feature request related to a problem? Please describe.**
There is no way to easily migrate from the old flow to the new flow without downtime.

**Describe the solution you'd like**
There should be a way to make a smooth migration. Probably, the simplest way would be to the modifying name of custom types and interfaces since v12 (as it would be another breaking change), e.g. adding -v2 suffix. So we could register them in both versions in commercetools project, migrate the code of the application, test it, and after everything works fine - remove the old one.

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x CommerceTools integration has changed ownership. From July 1st 2023, Adyen has taken over support / maintenance tasks for this integration from CommerceTools. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
