### ISSUE TITLE
Payment Method for ApplePay/GPay

### ISSUE THREAD

**Issue by LSshopmacher** [Adyen/adyen-commercetools#1106]
**Describe the bug**
CommerceTools Payment method is not set to ApplePay or GPay.

**To Reproduce**
Buy something with ApplePay/GPay and check Payment Tab in Commercetools.

**Screenshots**
![image](https://github.com/Adyen/adyen-commercetools/assets/93180076/51543718-201b-4d71-bb2c-fa981fd1cfec)

**Additional context**
The Adyen return is something like this (the **method:"applepay"** is clearly shown):
```{"id":"1608d72f","version":1,"versionModifiedAt":"2023-08-14T06:02:41.733Z","lastMessageSequenceNumber":1,"createdAt":"2023-08-14T06:02:41.733Z","lastModifiedAt":"2023-08-14T06:02:41.733Z","lastModifiedBy":{"clientId":"test","isPlatformClient":false},"createdBy":{"clientId":"test","isPlatformClient":false},"key":"test","amountPlanned":{"type":"centPrecision","currencyCode":"EUR","centAmount":25300,"fractionDigits":2},"paymentMethodInfo":{"paymentInterface":"adyen","method":"applepay"}},"paymentStatus":{"interfaceCode":"init"},"transactions":[],"interfaceInteractions":[]}```

**Comment by LSshopmacher** [comment]
any news on this? The client cannot use apple and google pay because it shows up as "visa" in his order management system.

**Comment by merijndebeer-adyen** [comment]
Dear Sender, we are closing this ticket on Github since its currently already in process with Adyen Support.
