### ISSUE TITLE
"BadRequest: The type with the key 'ctp-adyen-integration-interaction-notification' was not found

### ISSUE THREAD

**Issue by daviddamilola** [Adyen/adyen-commercetools#1116]
**Describe the bug**
after a payment is authorised on adyen, the notification module throws this error
```
cause: {
message: "The type with the key 'ctp-adyen-integration-interaction-notification' was not found"
name: "BadRequest"
code: 400
stack: "BadRequest: The type with the key 'ctp-adyen-integration-interaction-notification' was not found
    at createError (/app/node_modules/@commercetools/sdk-middleware-http/dist/sdk-middleware-http.cjs.js:241:29)
    at /app/node_modules/@commercetools/sdk-middleware-http/dist/sdk-middleware-http.cjs.js:423:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}
hostname: "localhost"
msg: "Unexpected exception occurred."
name: "ctp-adyen-integration-notifications"
v: 0
pid: 1
```

**To Reproduce**
1. follow the guide to deploy the notification module
2. process a payment in adyen web component
3. the notification module should receive the authorisation event with the error

**Comment by logeecom** [comment]
Hello David,

Please note that our team has reviewed your inquiry.

Based on the error message it looks like custom [payment interface interaction types](https://github.com/Adyen/adyen-commercetools/blob/master/notification/resources/payment-interface-interaction-type.json) are not set up correctly in commercetools instance. Please use [these instructions](https://github.com/Adyen/adyen-commercetools/blob/master/notification/docs/HowToRun.md#commercetools-project-requirements) to run **npm run setup-resources** command and ensure the set up of custom [payment interface interaction types](https://github.com/Adyen/adyen-commercetools/blob/master/notification/resources/payment-interface-interaction-type.json).

If you have any further questions or concerns, please let us know. We will gladly assist you.

Kind regards.

**Comment by daviddamilola** [comment]
> Hello David,
> 
> Please note that our team has reviewed your inquiry.
> 
> Based on the error message it looks like custom [payment interface interaction types](https://github.com/Adyen/adyen-commercetools/blob/master/notification/resources/payment-interface-interaction-type.json) are not set up correctly in commercetools instance. Please use [these instructions](https://github.com/Adyen/adyen-commercetools/blob/master/notification/docs/HowToRun.md#commercetools-project-requirements) to run **npm run setup-resources** command and ensure the set up of custom [payment interface interaction types](https://github.com/Adyen/adyen-commercetools/blob/master/notification/resources/payment-interface-interaction-type.json).
> 
> If you have any further questions or concerns, please let us know. We will gladly assist you.
> 
> Kind regards.

Thanks this works 🚀
