### ISSUE TITLE
Copy "PSP-reference" to the field  "interfaceId"

### ISSUE THREAD

**Issue by andihalberkamp** [Adyen/adyen-commercetools#1126]
**Is your feature request related to a problem? Please describe.**
We are using Adyan as payment-provider in our webshop. After an order is created the shopmanager wants easily find its related payment in the Adyan ui using its "Psp reference".
Unfortunaly this "PSP-reference" is not shown in the ct merchant within the "order section". So the shopmanager has to go to the api-playground, open the desired paymentmode and copy its key, which is equal to the "psp-reference". This process is not very User-friendly. 

**Describe the solution you'd like**
To improve on that it would be great if the "PSP-reference" could be saved in the "interfaceId" field of the payment-object. In this case the "PSP-reference" would be shown  automatically in the MC within the field "Payment provider ID"

![Bildschirm­foto 2023-12-29 um 13 25 33](https://github.com/Adyen/adyen-commercetools/assets/120093696/c804cd30-c152-4beb-8e56-177968cbb674)

**Comment by andihalberkamp** [comment]
fyi @merijndebeer-adyen

**Comment by merijndebeer-adyen** [comment]
Hi @andihalberkamp, thank you for this suggestion. We will add it to the backlog and keep you updated.

**Comment by logeecom** [comment]
He @andihalberkamp,
We appreciate your suggestion. After careful consideration, we have decided not to proceed with it at the moment. However,  your suggestion has been noted and added to our internal backlog.

Thank you!
