### ISSUE TITLE
Integration assumes prices are always including tax

### ISSUE THREAD

**Issue by viniciusfabri** [Adyen/adyen-commercetools#1133]
**Describe the bug**
The integration always assumes the Product prices are including tax, while that might not always be the case

**To Reproduce**
1. Pre conditions: Commercetools environment with this integration configured, and `addCommercetoolsLineItems` set to true
2. In Commercetools, configure a Tax Category with Tax Rates that have **Include in Price = No**
3. Configure a product with a price and to use the tax rate configured on the previous step
4. Place an order for this product

**Expected behavior**
The `lineItems` sent to Adyen when creating the Payment Session have their totals correctly calculated

**Actual Behavior**
The `lineItems` are incorrectly calculated
```
{
   "amountExcludingTax":0,
   "amountIncludingTax":1300,
   "description":"PRODUCT NAME",
   "id":"PRODUCTSKU",
   "quantity":2,
   "taxAmount":0,
   "taxPercentage":2100
}
```

The values above should be:
```
{
   "amountExcludingTax":1300,
   "amountIncludingTax":1573,
   "description":"PRODUCT NAME",
   "id":"PRODUCTSKU",
   "quantity":2,
   "taxAmount":273,
   "taxPercentage":2100
}
```

**Additional context**
The Tax object has a `includedInPrice` boolean value which can be checked to decide how to calculate the lineItems totals

**Comment by logeecom** [comment]
Hello @viniciusfabri 

We have resolved the issue that was reported, and now the request includes correct values for amountExcludingTax, amountIncludingTax, and taxAmount for line items. We tested it and the plugin behaves as expected.
Please note that we released a new version of CT modules https://github.com/Adyen/adyen-commercetools/releases/tag/v11.4.0.

Best regards.

**Comment by viniciusfabri** [comment]
@logeecom thank you! I won't be able to test this in the foreseeable future, so I'll close the ticket considering this done

Thanks again for the quick turnaround
