### ISSUE TITLE
 Future of commercetools-payment-to-order-processor

### ISSUE THREAD

**Issue by maxpagels** [Adyen/adyen-commercetools#1134]
Hi,

Per docs, for possible cases where payment is successful but the redirect fails and an order is not created, the suggestion is to use e.g. https://github.com/commercetools/commercetools-payment-to-order-processor. However, this implementation is archived, which makes me think it should not be actively used. I contacted commercetools' support who suggested it was archived during the handover of the payment extension code to adyen; is there any replacement available?

Thanks!

**Comment by butenkor** [comment]
The only reason why the linked repo is archived is that it is not actively maintained anymore. You can either use it, fork it or use as a reference for your own custom implementation.

**Comment by maxpagels** [comment]
@butenkor thanks, my question is does Adyen offer an alternative? We already use the implementation as-is.

If Adyen does not offer this functionality in some other package., feel free to close the issue.

**Comment by logeecom** [comment]
Hey all,
We appreciate your suggestion. After careful consideration, we have decided not to proceed with it at the moment. However,  your suggestion has been noted and added to our internal backlog.

Thank you!
