### ISSUE TITLE
Default `adyenPaymentMethodsToNames` in config is not localized which causes update payment fails

### ISSUE THREAD

**Issue by badz0** [Adyen/adyen-commercetools#1137]
**Describe the bug**
Seems like in the extension default `adyenPaymentMethodsToNames` was localized but in the notification not.
Please check the code for [extension](https://github.com/Adyen/adyen-commercetools/blob/master/extension/src/config/config.js#L117) and [notification](https://github.com/Adyen/adyen-commercetools/blob/master/notification/src/config/config.js#L69).
So when action `setMethodInfoName` is passed without localized name update payment fails.

**Comment by logeecom** [comment]
Hey,

Please note that we released a new version of CT modules https://github.com/Adyen/adyen-commercetools/releases/tag/v11.4.0.

Best regards.
