### ISSUE TITLE
Commercetools Project Key Fallback Behavior does not support API Gateway payloadFormatVersion 1.0

### ISSUE THREAD

**Issue by viniciusfabri** [Adyen/adyen-commercetools#1145]
**Describe the bug**
In our integration we're seeing that 90% of events coming from Adyen do not contain the `metadata.ctProjectKey` so we tried implementing the fallback behavior described [here](https://github.com/Adyen/adyen-commercetools/blob/master/notification/docs/IntegrationGuide.md#fallback-in-case-metadata-is-not-available). It did not work and after some investigation we've found that it's because the Adyen integration looks at `event.rawPath` to get the request path, but that's only available on API Gateway PayloadFormatResponse 2.0. On 1.0 the value is available on `event.path`

https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format

**To Reproduce**
1. Install this integration with commercetools (particularly the notification module)
2. Make sure this Lambda is using API Gateway PayloadFormatResponse 1.0 (or manually send an event with that format)
3. Omit the Commercetools Project Key from this event also
4. Ensure the Lambda trigger URL contains the CT Project Key as the last part of the URL (see fallback behavior documentation)

**Expected behavior**
The integration is able to figure out the project key from the URL

**Actual result**
Getting the following error:
```
        "message": "Notification can not be processed as \"metadata.ctProjectKey\" was not found on the notification nor the path is containing the commercetools project key.",
```

**Additional context**
To address this we customized our integration a bit to set `event.rawPath` with the value from `event.path`

For the actual integration I see two possible fixes:
- Modify [this line](https://github.com/Adyen/adyen-commercetools/blob/71265585459ea9728403815b8a68824dc5c07dfc/notification/index.lambda.js#L26) to use `event.path` if `event.rawPath` is not set
- Update documentation to ensure API Gateway is configured to use payload version 2.0

**Comment by logeecom** [comment]
Hello @viniciusfabri,

Thank you very much for your suggestion.

The code has been updated on our end, and changes will be available with our next release.

Kind regards.

**Comment by viniciusfabri** [comment]
hi @logeecom any timeline on the new release? On my project we're a few versions behind, we'd like to update it and remove our workarounds for this bug and #1133

**Comment by logeecom** [comment]
Hey @viniciusfabri 

The new [version 11.4.1](https://github.com/Adyen/adyen-commercetools/releases/tag/v11.4.1) has been released.

Best regards.
