### ISSUE TITLE
Payment validation fails for non Adyen payments 

### ISSUE THREAD

**Issue by tomwscott** [Adyen/adyen-commercetools#1151]
The extension expects all payments created in CommerceTools to be Adyen payments with the appropriate custom field and type configured otherwise it fails [validation](https://github.com/Adyen/adyen-commercetools/blob/f3751ed60e4b734789fecb803edfd1048376e98f/extension/src/paymentHandler/payment-handler.js#L36). If, however, we want to run another payment provider in parallel we are forced to ensure that the custom fields are setup correctly with `adyenMerchantAccount` and `commercetoolsProjectKey`

Proposal:

The extension handler should return immediately with a `200` if the `custom.type` is not `ctp-adyen-integration-web-components-payment-type` so that other payments are ignored by the extension

**Comment by butenkor** [comment]
Hi, did you follow the guide [here](https://github.com/Adyen/adyen-commercetools/blob/f3751ed60e4b734789fecb803edfd1048376e98f/extension/docs/HowToRun.md#commercetools-project-requirements) which links below to the following extension example [JSON](https://github.com/Adyen/adyen-commercetools/blob/f3751ed60e4b734789fecb803edfd1048376e98f/extension/resources/api-extension.json#L11). Line 11 ensures that extension is only triggered if the condition is fulfilled.

**Comment by logeecom** [comment]
Hey,

Thank you @butenkor  for your help!
This is indeed the condition under which CommerceTools triggers our extension. 
Please @tomwscott check if you have paymentMethodInfo.paymentInterface set to ctp-adyen-integration value for a CommerceTools payment you have problems with.

Best regards.
