### ISSUE TITLE
Production notification module extensions throws an error "Cannot read properties of undefined (reading 'custom')"

### ISSUE THREAD

**Issue by daviddamilola** [Adyen/adyen-commercetools#1154]
**Describe the bug**
Production notification module extensions throws an error "Cannot read properties of undefined (reading 'custom')" when a notification is received from adyen.

**To Reproduce**
1. follow steps to deploy extension module

this error is gotten in the notification extension
```
cause: {
message: "Cannot read properties of undefined (reading 'custom')"
name: "TypeError"
stack: "TypeError: Cannot read properties of undefined (reading 'custom')
    at Object.processNotification (file:///app/src/handler/notification/notification.handler.js:59:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleNotification (file:///app/src/api/notification/notification.controller.js:27:7)
    at async Server.<anonymous> (file:///app/src/server.js:20:9)"
}

```
the payload in the notification is
```
notification: [
0: {
eventCode: "AUTHORISATION"
eventDate: "2024-03-20T13:13:06+01:00"
pspReference: "*****************"
success: "true"
}]
pid: 1
v: 0
}

```

**Expected behavior**
The notification module correctly updates the order in CT, 

**Screenshots**

**Desktop (please complete the following information):**
 not applicable

**Smartphone (please complete the following information):**
not applicable

**Additional context**
the payment object in ct had previously failed payments from mismatching ctProjectKey.

**Comment by logeecom** [comment]
Hey @daviddamilola 

We have found and fixed the issue. The fix is available on the master branch and it will be available in the next integration release.
Our team will let you know once the new version is released.

Best regards.

**Comment by logeecom** [comment]
Hey,

The new version has been released:

[Release v11.4.2 · Adyen/adyen-commercetools](https://github.com/Adyen/adyen-commercetools/releases/tag/v11.4.2)

Best regards.
