### ISSUE TITLE
logLevel parameter does not have any effect on "Extension Module Lambda Handler" (extension/index.lambda.js)

### ISSUE THREAD

**Issue by kaplansin** [Adyen/adyen-commercetools#1161]
**Is your feature request related to a problem? Please describe.**
Extension Module Lambda handler does not log any request, setting logLevel parameter to DEBUG or TRACE does not have any effect.
We would like to monitor Request/Response and their content for our development processes. 
Same setting works for Notification Module Lambda handler and we can trace each request after enabling logLevel parameter.

**Describe the solution you'd like**
We do see logging mechanic
extension/src/api/payment/payment.controller.js
Adding Request/Response logger also in extension/index.lambda.js would be a good improvement for development processes.

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by logeecom** [comment]
Hello @kaplansin,

Note that we’ve released a new version of the [integration](https://github.com/Adyen/adyen-commercetools/releases/tag/v11.5.1).

Kind regards.
