### ISSUE TITLE
Documentation for drop-in integration

### ISSUE THREAD

**Issue by vasily-polonsky** [Adyen/adyen-commercetools#1214]
**Is your feature request related to a problem? Please describe.**
We used this extension/notification to build the integration between commercetools and adyen with Advanced Flow. And on the frontend we use DropIn, not Components. And so far everything is working fine, but we recently noticed that in the documentation in this repo it says 

> commercetools-adyen-integration provides an [Adyen Web Components](https://docs.adyen.com/checkout/components-web) based integration between the commercetools and Adyen PSP.

There is no information about if on frontend uses DroipIn, will everything work well or is there possibility that we may face possible problems in the future?

**Describe the solution you'd like**
Would be nice to have in documentation info about DropIn support for this repo.

**Comment by adyen-integrations-support** [comment]
Hello Vasily,

Thank you for reaching out. This is just a quick note to inform you that we received your ticket.

We will take this issue into consideration as soon as possible.

Best regards

**Comment by vasily-polonsky** [comment]
Hi there,

as we are switching to web components, this issue is not relevant anymore

Thanks
