### ISSUE TITLE
addTransaction from the extension does not add a timestamp

### ISSUE THREAD

**Issue by jakob-tonies** [Adyen/adyen-commercetools#1224]
### Problem

When a transaction is added to a Commercetools payment via an `addTransaction` action through the extension module then it does NOT include a `timestamp`.

This means that in Commercetools you end up with a mix of transactions some with a timestamp and some without. Which is not great for debugging.

https://github.com/Adyen/adyen-commercetools/blob/master/extension/src/paymentHandler/payment-utils.js#L108

### Expected

I would expect that a `timestamp` is added in the same way as it happens in a `addTransaction` action in the notification module.  See https://github.com/Adyen/adyen-commercetools/blob/master/notification/src/handler/notification/notification.handler.js#L509

**Comment by adyen-integrations-support** [comment]
Hi @jakob-tonies ,

We have added in extension module to include a timestamp in addTransaction action. This update will be released in one of the next release versions. Once the update is available, I’ll let you know.

Thank you for your patience, and please feel free to reach out if you have any further questions or concerns.

Best regards,

**Comment by adyen-integrations-support** [comment]
Hi @jakob-tonies ,

We wanted to let you know that we have released a new version of the plugin v11.5.9 that addresses this issue. You can download it at this link: https://github.com/Adyen/adyen-commercetools/releases/tag/v11.5.9 

Could you please confirm if everything is working well now with the new release?

Best regards

**Comment by jakob-tonies** [comment]
Thank you very much
